// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_BottomPanel;
void ui_event_PreviousContainer(lv_event_t * e);
lv_obj_t * ui_PreviousContainer;
void ui_event_PreviousButton(lv_event_t * e);
lv_obj_t * ui_PreviousButton;
void ui_event_NextContainer(lv_event_t * e);
lv_obj_t * ui_NextContainer;
void ui_event_NextButton(lv_event_t * e);
lv_obj_t * ui_NextButton;
void ui_event_IconEQ(lv_event_t * e);
lv_obj_t * ui_IconEQ;
void ui_event_IconGate(lv_event_t * e);
lv_obj_t * ui_IconGate;
void ui_event_IconAmp(lv_event_t * e);
lv_obj_t * ui_IconAmp;
void ui_event_IconCab(lv_event_t * e);
lv_obj_t * ui_IconCab;
void ui_event_IconComp(lv_event_t * e);
lv_obj_t * ui_IconComp;
void ui_event_IconMod(lv_event_t * e);
lv_obj_t * ui_IconMod;
void ui_event_IconDelay(lv_event_t * e);
lv_obj_t * ui_IconDelay;
void ui_event_IconReverb(lv_event_t * e);
lv_obj_t * ui_IconReverb;
void ui_event_SettingsImage(lv_event_t * e);
lv_obj_t * ui_SettingsImage;
lv_obj_t * ui_TopPanel;
lv_obj_t * ui_IKLogo;
lv_obj_t * ui_BTStatusConn;
void ui_event_BTStatusDisconn(lv_event_t * e);
lv_obj_t * ui_BTStatusDisconn;
lv_obj_t * ui_USBStatusOK;
lv_obj_t * ui_USBStatusFail;
lv_obj_t * ui_WiFiStatusConn;
lv_obj_t * ui_WiFiStatusDisconn;
lv_obj_t * ui_ProjectHeadingLabel;
lv_obj_t * ui_Skins;
lv_obj_t * ui_SkinImage;
void ui_event_PresetHeadingLabel(lv_event_t * e);
lv_obj_t * ui_PresetHeadingLabel;
lv_obj_t * ui_BankTitleLabel;
lv_obj_t * ui_BankValueLabel;
lv_obj_t * ui_BPMTitleLabel;
lv_obj_t * ui_BPMValueLabel;
lv_obj_t * ui_BPMIndicator;
void ui_event_PresetDetailsTextArea(lv_event_t * e);
lv_obj_t * ui_PresetDetailsTextArea;
void ui_event_LeftArrow(lv_event_t * e);
lv_obj_t * ui_LeftArrow;
void ui_event_RightArrow(lv_event_t * e);
lv_obj_t * ui_RightArrow;
void ui_event_EntryKeyboard(lv_event_t * e);
lv_obj_t * ui_EntryKeyboard;
void ui_event_OKTick(lv_event_t * e);
lv_obj_t * ui_OKTick;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
lv_obj_t * ui_Settings;
lv_obj_t * ui_SettingsPanel;
lv_obj_t * ui_SwitchRow1;
lv_obj_t * ui_Switch1Group;
lv_obj_t * ui_Switch1Label;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Switch2Group;
lv_obj_t * ui_Switch2Label;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
lv_obj_t * ui_SwitchRow2;
lv_obj_t * ui_Switch3Group;
lv_obj_t * ui_Switch3Label;
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Switch4Group;
lv_obj_t * ui_Switch4Label;
void ui_event_Switch4(lv_event_t * e);
lv_obj_t * ui_Switch4;
lv_obj_t * ui_SelectGroup;
lv_obj_t * ui_Select1Label;
void ui_event_Select1(lv_event_t * e);
lv_obj_t * ui_Select1;
lv_obj_t * ui_Slider1Group;
lv_obj_t * ui_Slider1Label;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Slider1Value;
lv_obj_t * ui_Slider2Group;
lv_obj_t * ui_Slider2Label;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Slider2Value;
lv_obj_t * ui_Slider3Group;
lv_obj_t * ui_Slider3Label;
void ui_event_Slider3(lv_event_t * e);
lv_obj_t * ui_Slider3;
lv_obj_t * ui_Slider3Value;
lv_obj_t * ui_Slider4Group;
lv_obj_t * ui_Slider4Label;
void ui_event_Slider4(lv_event_t * e);
lv_obj_t * ui_Slider4;
lv_obj_t * ui_Slider4Value;
lv_obj_t * ui_Slider5Group;
lv_obj_t * ui_Slider5Label;
void ui_event_Slider5(lv_event_t * e);
lv_obj_t * ui_Slider5;
lv_obj_t * ui_Slider5Value;
lv_obj_t * ui_Slider6Group;
lv_obj_t * ui_Slider6Label;
void ui_event_Slider6(lv_event_t * e);
lv_obj_t * ui_Slider6;
lv_obj_t * ui_Slider6Value;
lv_obj_t * ui_Slider7Group;
lv_obj_t * ui_Slider7Label;
void ui_event_Slider7(lv_event_t * e);
lv_obj_t * ui_Slider7;
lv_obj_t * ui_Slider7Value;
void ui_event_SettingsTabview(lv_event_t * e);
lv_obj_t * ui_SettingsTabview;
lv_obj_t * ui_NoiseGateTab;
lv_obj_t * ui_CompressorTab;
lv_obj_t * ui_EQTab;
lv_obj_t * ui_ReverbPage;
lv_obj_t * ui_Modulation;
lv_obj_t * ui_Delay;
lv_obj_t * ui_Amplifier;
lv_obj_t * ui_Global;
lv_obj_t * ui_Exit;
void ui_event_CloseImage(lv_event_t * e);
lv_obj_t * ui_CloseImage;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_PreviousContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PreviousClicked(e);
    }
}

void ui_event_PreviousButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PreviousClicked(e);
    }
}

void ui_event_NextContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        NextClicked(e);
    }
}

void ui_event_NextButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        NextClicked(e);
    }
}

void ui_event_IconEQ(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_screen_init);
        show_settings_tab(e);
    }
}

void ui_event_IconGate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        toggle_effect_gate(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_screen_init);
        show_settings_tab(e);
    }
}

void ui_event_IconAmp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        toggle_effect_amp(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_screen_init);
        show_settings_tab(e);
    }
}

void ui_event_IconCab(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        toggle_effect_cab(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_screen_init);
        show_settings_tab(e);
    }
}

void ui_event_IconComp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        toggle_effect_comp(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        show_settings_tab(e);
    }
}

void ui_event_IconMod(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        toggle_effect_mod(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_screen_init);
        show_settings_tab(e);
    }
}

void ui_event_IconDelay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        toggle_effect_delay(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_screen_init);
        show_settings_tab(e);
    }
}

void ui_event_IconReverb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        toggle_effect_reverb(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_Settings_screen_init);
        show_settings_tab(e);
    }
}

void ui_event_SettingsImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Settings_screen_init);
    }
}

void ui_event_BTStatusDisconn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        BTBondsClearRequest(e);
    }
}

void ui_event_PresetHeadingLabel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_flag_modify(ui_LeftArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_RightArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_PresetDetailsTextArea, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_OKTick, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_BankTitleLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_BankValueLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_BPMTitleLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_BPMValueLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_BPMIndicator, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_PresetDetailsTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_keyboard_set_target(ui_EntryKeyboard,  ui_PresetDetailsTextArea);
        _ui_flag_modify(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_LeftArrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        AmpSkinPrevious(e);
    }
}

void ui_event_RightArrow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        AmpSkinNext(e);
    }
}

void ui_event_EntryKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        PresetDescriptionChanged(e);
    }
}

void ui_event_OKTick(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PresetDescriptionChanged(e);
        SaveUserDataRequest(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_OKTick, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_LeftArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_RightArrow, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_PresetDetailsTextArea, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_BankTitleLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_BankValueLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_BPMTitleLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_BPMValueLabel, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_BPMIndicator, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
}

void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
}

void ui_event_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
}

void ui_event_Select1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ParameterChanged(e);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Slider1Value, target, "", "");
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Slider2Value, target, "", "");
    }
}

void ui_event_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Slider3Value, target, "", "");
    }
}

void ui_event_Slider4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Slider4Value, target, "", "");
    }
}

void ui_event_Slider5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Slider5Value, target, "", "");
    }
}

void ui_event_Slider6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Slider6Value, target, "", "");
    }
}

void ui_event_Slider7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_RELEASED) {
        ParameterChanged(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Slider7Value, target, "", "");
    }
}

void ui_event_SettingsTabview(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        UI_SettingsTabChanged(e);
    }
}

void ui_event_CloseImage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Settings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
