// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: TonexOneController_1.69pj

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_PresetHeadingLabel;
lv_obj_t * ui_BPMLabel;
lv_obj_t * ui_BPM;
lv_obj_t * ui_CStatus;
lv_obj_t * ui_MStatus;
lv_obj_t * ui_DStatus;
lv_obj_t * ui_RStatus;
lv_obj_t * ui_BottomContainer;
lv_obj_t * ui_PresetHeadingLabel2;
lv_obj_t * ui_TopPanel;
lv_obj_t * ui_USBStatusOK;
lv_obj_t * ui_USBStatusFail;
lv_obj_t * ui_Logo;
lv_obj_t * ui_BTStatusDisconn;
lv_obj_t * ui_BTStatusConn;
lv_obj_t * ui_WiFiStatusDisconn;
lv_obj_t * ui_WiFiStatusConn;
void ui_event_TouchGestureContainer(lv_event_t * e);
lv_obj_t * ui_TouchGestureContainer;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_TouchGestureContainer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        NextClicked(e);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        PreviousClicked(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
