/*
 Copyright (C) 2025  Greg Smith

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 
*/


#ifndef _VALETON_PARAMS_H
#define _VALETON_PARAMS_H

#ifdef __cplusplus
extern "C" {
#endif

enum ValetonEffectBlocks
{
    VALETON_EFFECT_BLOCK_NR,
    VALETON_EFFECT_BLOCK_PRE,
    VALETON_EFFECT_BLOCK_DST,
    VALETON_EFFECT_BLOCK_AMP,
    VALETON_EFFECT_BLOCK_CAB,
    VALETON_EFFECT_BLOCK_EQ,
    VALETON_EFFECT_BLOCK_MOD,
    VALETON_EFFECT_BLOCK_DLY,
    VALETON_EFFECT_BLOCK_RVB,
    VALETON_EFFECT_BLOCK_NS,
    VALETON_EFFECT_BLOCK_LAST
};

enum ValetonValetonEffectNR
{
    VALETON_EFFECT_NR_GATE
};

enum ValetonEffectPre
{
    VALETON_EFFECT_PRE_COMP,
    VALETON_EFFECT_PRE_COMP4,
    VALETON_EFFECT_PRE_BOOST,
    VALETON_EFFECT_PRE_MICRO_BOOST,
    VALETON_EFFECT_PRE_B_BOOST,
    VALETON_EFFECT_PRE_TOUCHER,
    VALETON_EFFECT_PRE_CRIER,
    VALETON_EFFECT_PRE_OCTA,
    VALETON_EFFECT_PRE_PITCH,
    VALETON_EFFECT_PRE_DETUNE
};

enum ValetonEffectDist
{
    VALETON_EFFECT_DIST_GREEN_OD,
    VALETON_EFFECT_DIST_YELLOW_OD,
    VALETON_EFFECT_DIST_SUPER_OD,
    VALETON_EFFECT_DIST_SM_DIST,
    VALETON_EFFECT_DIST_PLUSTORTION,
    VALETON_EFFECT_DIST_LA_CHARGER,
    VALETON_EFFECT_DIST_DARKTALE,
    VALETON_EFFECT_DIST_SORA_FUZZ,
    VALETON_EFFECT_DIST_RED_HAZE,
    VALETON_EFFECT_DIST_BASS_OD
};

enum ValetonEffectEQ
{
    VALETON_EFFECT_EQ_GUITAR_EQ1,
    VALETON_EFFECT_EQ_GUITAR_EQ2,
    VALETON_EFFECT_EQ_BASS_EQ1,
    VALETON_EFFECT_EQ_BASS_EQ2,
    VALETON_EFFECT_EQ_MESS_EQ
};

enum ValetonEffectMod
{
    VALETON_EFFECT_MOD_A_CHORUS,
    VALETON_EFFECT_MOD_B_CHORUS,
    VALETON_EFFECT_MOD_JET,
    VALETON_EFFECT_MOD_N_JET,
    VALETON_EFFECT_MOD_O_PHASE,
    VALETON_EFFECT_MOD_M_VIBE,
    VALETON_EFFECT_MOD_V_ROTO,
    VALETON_EFFECT_MOD_VIBRATO,
    VALETON_EFFECT_MOD_O_TREM,
    VALETON_EFFECT_MOD_SINE_TREM,
    VALETON_EFFECT_MOD_BIAS_TREM
};

enum ValetonEffectDly
{
    VALETON_EFFECT_DLY_PURE,
    VALETON_EFFECT_DLY_ANALOG,
    VALETON_EFFECT_DLY_SLAPBACK,
    VALETON_EFFECT_DLY_SWEET_ECHO,
    VALETON_EFFECT_DLY_TAPE,
    VALETON_EFFECT_DLY_TUBE,
    VALETON_EFFECT_DLY_REV_ECHO,
    VALETON_EFFECT_DLY_RING_ECHO,
    VALETON_EFFECT_DLY_SWEEP_ECHO,
    VALETON_EFFECT_DLY_PING_PONG
};

enum ValetonEffectRvb
{   
    VALETON_EFFECT_RVB_AIR,
    VALETON_EFFECT_RVB_ROOM,
    VALETON_EFFECT_RVB_HALL,
    VALETON_EFFECT_RVB_CHURCH,
    VALETON_EFFECT_RVB_PLATE_L,
    VALETON_EFFECT_RVB_PLATE,
    VALETON_EFFECT_RVB_SPRING,
    VALETON_EFFECT_RVB_N_STAR,
    VALETON_EFFECT_RVB_DEEPSEA,
    VALETON_EFFECT_RVB_SWEET_SPACE
};

enum ValetonEffectCab
{  
    VALETON_EFFECT_CAB_TWD_CP,
    VALETON_EFFECT_CAB_DARK_VIT,
    VALETON_EFFECT_CAB_FOXY_1X12,
    VALETON_EFFECT_CAB_L_STAR_1X12,
    VALETON_EFFECT_CAB_DARK_CS_2X12,
    VALETON_EFFECT_CAB_DARK_TWIN_2X12,
    VALETON_EFFECT_CAB_SUP_STAR_2X12,
    VALETON_EFFECT_CAB_J_120_2X12,
    VALETON_EFFECT_CAB_FOXY_2X12,
    VALETON_EFFECT_CAB_UK_GRN_2X12,
    VALETON_EFFECT_CAB_UK_GRN_4X12,
    VALETON_EFFECT_CAB_BOG_4X12,
    VALETON_EFFECT_CAB_DIZZ_4X12,
    VALETON_EFFECT_CAB_EV_4X12,
    VALETON_EFFECT_CAB_SOLO_4X12,
    VALETON_EFFECT_CAB_MESS_4X12,
    VALETON_EFFECT_CAB_EAGLE_4X12,
    VALETON_EFFECT_CAB_JUICE_4X12,
    VALETON_EFFECT_CAB_BELLMAN_2X12,
    VALETON_EFFECT_CAB_AMPG_4X10
};

enum ValetonEffectAmp
{  
    VALETON_EFFECT_AMP_TWEEDY,
    VALETON_EFFECT_AMP_BELLMAN_59N,
    VALETON_EFFECT_AMP_DARK_TWIN,
    VALETON_EFFECT_AMP_FOXY_30N,
    VALETON_EFFECT_AMP_J_120_CL,
    VALETON_EFFECT_AMP_MATCH_CL,
    VALETON_EFFECT_AMP_L_STAR_CL,
    VALETON_EFFECT_AMP_UK_45,
    VALETON_EFFECT_AMP_UK_50JP,
    VALETON_EFFECT_AMP_UK_800,
    VALETON_EFFECT_AMP_BELLMAN_59B,
    VALETON_EFFECT_AMP_FOXY_30TB,
    VALETON_EFFECT_AMP_SUPDUAL_OD,
    VALETON_EFFECT_AMP_SOLO100_OD,
    VALETON_EFFECT_AMP_Z38_OD,
    VALETON_EFFECT_AMP_BAD_KT_OD,
    VALETON_EFFECT_AMP_JUICEW_R100,
    VALETON_EFFECT_AMP_DIZZ_VH,
    VALETON_EFFECT_AMP_DIZZ_VH_PLUS,
    VALETON_EFFECT_AMP_EAGLE_120,
    VALETON_EFFECT_AMP_EV_51,
    VALETON_EFFECT_AMP_SOLO100_LD,
    VALETON_EFFECT_AMP_MESS_DUALV,
    VALETON_EFFECT_AMP_MESS_DUALM,
    VALETON_EFFECT_AMP_POWER_LD,
    VALETON_EFFECT_AMP_FLAGMAN_PLUS,
    VALETON_EFFECT_AMP_BOG_REDV,
    VALETON_EFFECT_AMP_CLASSIC_BASS,
    VALETON_EFFECT_AMP_FOXY_BASS,
    VALETON_EFFECT_AMP_MESS_BASS,
    VALETON_EFFECT_AMP_AC_PRE1,
    VALETON_EFFECT_AMP_AC_PRE2
};

// markers for special params
#define VALETON_BLOCK_SELECTION     0xFF        // select which Pedal in block
#define VALETON_BLOCK_ENABLE        0xFE        // enable block

enum ValetonParameters
{
    // block enables
    VALETON_PARAM_NR_ENABLE,  
    VALETON_PARAM_PRE_ENABLE,
    VALETON_PARAM_DIST_ENABLE,
    VALETON_PARAM_AMP_ENABLE,
    VALETON_PARAM_CAB_ENABLE,
    VALETON_PARAM_EQ_ENABLE,
    VALETON_PARAM_MOD_ENABLE,
    VALETON_PARAM_DLY_ENABLE,
    VALETON_PARAM_RVB_ENABLE,
    VALETON_PARAM_NS_ENABLE,

    // models
    VALETON_PARAM_NR_TYPE,
    VALETON_PARAM_PRE_TYPE,
    VALETON_PARAM_DIST_TYPE,        
    VALETON_PARAM_AMP_TYPE,   
    VALETON_PARAM_CAB_TYPE,    
    VALETON_PARAM_EQ_TYPE,    
    VALETON_PARAM_MOD_TYPE,    
    VALETON_PARAM_DLY_TYPE,    
    VALETON_PARAM_RVB_TYPE,    
    VALETON_PARAM_NS_TYPE,

    // params
    //**** NR **** 
    VALETON_PARAM_NR_PARAM_0,
    VALETON_PARAM_NR_PARAM_1,
    VALETON_PARAM_NR_PARAM_2,
    VALETON_PARAM_NR_PARAM_3,
    VALETON_PARAM_NR_PARAM_4,
    VALETON_PARAM_NR_PARAM_5,
    VALETON_PARAM_NR_PARAM_6,
    VALETON_PARAM_NR_PARAM_7,

    //**** Pre ****
    VALETON_PARAM_PRE_PARAM_0,    
    VALETON_PARAM_PRE_PARAM_1,    
    VALETON_PARAM_PRE_PARAM_2,    
    VALETON_PARAM_PRE_PARAM_3,    
    VALETON_PARAM_PRE_PARAM_4,    
    VALETON_PARAM_PRE_PARAM_5,    
    VALETON_PARAM_PRE_PARAM_6,    
    VALETON_PARAM_PRE_PARAM_7,    
    
    //**** Dist ****
    VALETON_PARAM_DIST_PARAM_0,
    VALETON_PARAM_DIST_PARAM_1,
    VALETON_PARAM_DIST_PARAM_2,
    VALETON_PARAM_DIST_PARAM_3,
    VALETON_PARAM_DIST_PARAM_4,
    VALETON_PARAM_DIST_PARAM_5,
    VALETON_PARAM_DIST_PARAM_6,
    VALETON_PARAM_DIST_PARAM_7,

    //**** Amp ****
    VALETON_PARAM_AMP_PARAM_0,
    VALETON_PARAM_AMP_PARAM_1,
    VALETON_PARAM_AMP_PARAM_2,
    VALETON_PARAM_AMP_PARAM_3,
    VALETON_PARAM_AMP_PARAM_4,
    VALETON_PARAM_AMP_PARAM_5,
    VALETON_PARAM_AMP_PARAM_6,
    VALETON_PARAM_AMP_PARAM_7,

    //**** Cab ****
    VALETON_PARAM_CAB_PARAM_0,
    VALETON_PARAM_CAB_PARAM_1,
    VALETON_PARAM_CAB_PARAM_2,
    VALETON_PARAM_CAB_PARAM_3,
    VALETON_PARAM_CAB_PARAM_4,
    VALETON_PARAM_CAB_PARAM_5,
    VALETON_PARAM_CAB_PARAM_6,
    VALETON_PARAM_CAB_PARAM_7,

    //**** EQ ****  
    VALETON_PARAM_EQ_PARAM_0,
    VALETON_PARAM_EQ_PARAM_1,
    VALETON_PARAM_EQ_PARAM_2,
    VALETON_PARAM_EQ_PARAM_3,
    VALETON_PARAM_EQ_PARAM_4,
    VALETON_PARAM_EQ_PARAM_5,
    VALETON_PARAM_EQ_PARAM_6,
    VALETON_PARAM_EQ_PARAM_7,

    //**** Mod ****
    VALETON_PARAM_MOD_PARAM_0,
    VALETON_PARAM_MOD_PARAM_1,
    VALETON_PARAM_MOD_PARAM_2,
    VALETON_PARAM_MOD_PARAM_3,
    VALETON_PARAM_MOD_PARAM_4,
    VALETON_PARAM_MOD_PARAM_5,
    VALETON_PARAM_MOD_PARAM_6,
    VALETON_PARAM_MOD_PARAM_7,

    //**** Delay ****
    VALETON_PARAM_DLY_PARAM_0,
    VALETON_PARAM_DLY_PARAM_1,
    VALETON_PARAM_DLY_PARAM_2,
    VALETON_PARAM_DLY_PARAM_3,
    VALETON_PARAM_DLY_PARAM_4,
    VALETON_PARAM_DLY_PARAM_5,
    VALETON_PARAM_DLY_PARAM_6,
    VALETON_PARAM_DLY_PARAM_7,

    //**** Reverb ****
    VALETON_PARAM_RVB_PARAM_0,
    VALETON_PARAM_RVB_PARAM_1,
    VALETON_PARAM_RVB_PARAM_2,
    VALETON_PARAM_RVB_PARAM_3,
    VALETON_PARAM_RVB_PARAM_4,
    VALETON_PARAM_RVB_PARAM_5,
    VALETON_PARAM_RVB_PARAM_6,
    VALETON_PARAM_RVB_PARAM_7,

    //**** NS ****
    VALETON_PARAM_NS_PARAM_0,
    VALETON_PARAM_NS_PARAM_1,
    VALETON_PARAM_NS_PARAM_2,
    VALETON_PARAM_NS_PARAM_3,
    VALETON_PARAM_NS_PARAM_4,
    VALETON_PARAM_NS_PARAM_5,
    VALETON_PARAM_NS_PARAM_6,
    VALETON_PARAM_NS_PARAM_7,
    VALETON_PARAM_NS_PARAM_8,
    VALETON_PARAM_NS_PARAM_9,
    VALETON_PARAM_NS_PARAM_10,

    // must be last actual parameter
    VALETON_PARAM_LAST,

    // these are not parameters as such, but globals/special/set differently to the params above
    VALETON_GLOBAL_BPM,
    VALETON_GLOBAL_INPUT_TRIM,
    VALETON_GLOBAL_CABSIM_BYPASS,
    VALETON_GLOBAL_TUNING_REFERENCE,
    VALETON_GLOBAL_BYPASS,          
    VALETON_GLOBAL_MASTER_VOLUME, 

    // must be last actual global
    VALETON_GLOBAL_LAST
};

// special cases for handling effect switches that use Midi but don't change a parameter
#define VALETON_UNKNOWN           0xFFFF


esp_err_t valeton_params_init(void);
esp_err_t valeton_params_get_locked_access(tModellerParameter** param_ptr);
esp_err_t valeton_params_release_locked_access(void);
esp_err_t valeton_params_get_min_max(uint16_t param_index, float* min, float* max);
esp_err_t valeton_dump_parameters(void);
float valeton_params_clamp_value(uint16_t param_index, float value);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif