/*
 Copyright (C) 2025  Greg Smith

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 
*/


#ifndef _VALETON_PARAMS_H
#define _VALETON_PARAMS_H

#ifdef __cplusplus
extern "C" {
#endif

enum ValetonEffectBlocks
{
    VALETON_EFFECT_BLOCK_NR,
    VALETON_EFFECT_BLOCK_PRE,
    VALETON_EFFECT_BLOCK_DST,
    VALETON_EFFECT_BLOCK_EQ,
    VALETON_EFFECT_BLOCK_MOD,
    VALETON_EFFECT_BLOCK_DLY,
    VALETON_EFFECT_BLOCK_RVB
};

enum ValetonValetonEffectNR
{
    VALETON_EFFECT_NR_GATE
};

enum ValetonEffectPre
{
    VALETON_EFFECT_PRE_COMP,
    VALETON_EFFECT_PRE_COMP4,
    VALETON_EFFECT_PRE_BOOST,
    VALETON_EFFECT_PRE_MICRO_BOOST,
    VALETON_EFFECT_PRE_B_BOOST,
    VALETON_EFFECT_PRE_TOUCHER,
    VALETON_EFFECT_PRE_CRIER,
    VALETON_EFFECT_PRE_OCTA,
    VALETON_EFFECT_PRE_PITCH,
    VALETON_EFFECT_PRE_DETUNE
};

enum ValetonEffectDist
{
    VALETON_EFFECT_DIST_GREEN_OD,
    VALETON_EFFECT_DIST_YELLOW_OD,
    VALETON_EFFECT_DIST_SUPER_OD,
    VALETON_EFFECT_DIST_SM_DIST,
    VALETON_EFFECT_DIST_PLUSTORTION,
    VALETON_EFFECT_DIST_LA_CHARGER,
    VALETON_EFFECT_DIST_DARKTALE,
    VALETON_EFFECT_DIST_SORA_FUZZ,
    VALETON_EFFECT_DIST_RED_HAZE,
    VALETON_EFFECT_DIST_BASS_OD
};

enum ValetonEffectEQ
{
    VALETON_EFFECT_EQ_GUITAR_EQ1,
    VALETON_EFFECT_EQ_GUITAR_EQ2,
    VALETON_EFFECT_EQ_BASS_EQ1,
    VALETON_EFFECT_EQ_BASS_EQ2,
    VALETON_EFFECT_EQ_MESS_EQ
};

enum ValetonEffectMod
{
    VALETON_EFFECT_MOD_A_CHORUS,
    VALETON_EFFECT_MOD_B_CHORUS,
    VALETON_EFFECT_MOD_JET,
    VALETON_EFFECT_MOD_N_JET,
    VALETON_EFFECT_MOD_O_PHASE,
    VALETON_EFFECT_MOD_M_VIBE,
    VALETON_EFFECT_MOD_V_ROTO,
    VALETON_EFFECT_MOD_VIBRATOR,
    VALETON_EFFECT_MOD_O_TREM,
    VALETON_EFFECT_MOD_SINE_TREM,
    VALETON_EFFECT_MOD_BIAS_TREM
};

enum ValetonEffectDly
{
    VALETON_EFFECT_DLY_PURE,
    VALETON_EFFECT_DLY_ANALOG,
    VALETON_EFFECT_DLY_SLAPBACK,
    VALETON_EFFECT_DLY_SWEET_ECHO,
    VALETON_EFFECT_DLY_TAPE,
    VALETON_EFFECT_DLY_TUBE,
    VALETON_EFFECT_DLY_REV_ECHO,
    VALETON_EFFECT_DLY_RING_ECHO,
    VALETON_EFFECT_DLY_SWEEP_ECHO,
    VALETON_EFFECT_DLY_PING_PONG
};

enum ValetonEffectRvb
{   
    VALETON_EFFECT_RVB_AIR,
    VALETON_EFFECT_RVB_ROOM,
    VALETON_EFFECT_RVB_HALL,
    VALETON_EFFECT_RVB_CHURCH,
    VALETON_EFFECT_RVB_PLATE_L,
    VALETON_EFFECT_RVB_PLATE,
    VALETON_EFFECT_RVB_SPRING,
    VALETON_EFFECT_RVB_N_STAR,
    VALETON_EFFECT_RVB_DEEPSEA,
    VALETON_EFFECT_RVB_SWEET_SPACE
};

// markers for special params
#define VALETON_BLOCK_SELECTION     0xFF        // select which Pedal in block
#define VALETON_BLOCK_ENABLE        0xFE        // enable block

enum ValetonParameters
{
    //**** NR ****
    VALETON_PARAM_NR_ENABLE,    
    VALETON_PARAM_NR_THRESHOLD,

    //**** Pre ****
    VALETON_PARAM_PRE_ENABLE,
    VALETON_PARAM_PRE_TYPE,    
    // Comp
    VALETON_PARAM_PRE_COMP_SUSTAIN,
    VALETON_PARAM_PRE_COMP_VOL,
    // Comp4
    VALETON_PARAM_PRE_COMP4_SUSTAIN,
    VALETON_PARAM_PRE_COMP4_ATTACK,
    VALETON_PARAM_PRE_COMP4_VOL,
    VALETON_PARAM_PRE_COMP4_CLIP,
    // Boost
    VALETON_PARAM_PRE_BOOST_GAIN,
    VALETON_PARAM_PRE_BOOST_3DB,
    VALETON_PARAM_PRE_BOOST_BRIGHT,
    // Micro Boost
    VALETON_PARAM_PRE_MICRO_BOOST_GAIN,
    // B-Boost
    VALETON_PARAM_PRE_B_BOOST_GAIN,
    VALETON_PARAM_PRE_B_BOOST_VOL,
    VALETON_PARAM_PRE_B_BOOST_BASS,
    VALETON_PARAM_PRE_B_BOOST_TREBLE,
    // Toucher
    VALETON_PARAM_PRE_TOUCHER_SENSE,
    VALETON_PARAM_PRE_TOUCHER_RANGE,
    VALETON_PARAM_PRE_TOUCHER_Q,
    VALETON_PARAM_PRE_TOUCHER_MIX,
    VALETON_PARAM_PRE_TOUCHER_MODE,
    // Crier
    VALETON_PARAM_PRE_CRIER_DEPTH,
    VALETON_PARAM_PRE_CRIER_RATE,
    VALETON_PARAM_PRE_CRIER_VOL,
    VALETON_PARAM_PRE_CRIER_LOW,
    VALETON_PARAM_PRE_CRIER_Q,
    // Octa
    VALETON_PARAM_PRE_OCTA_LOW,
    VALETON_PARAM_PRE_OCTA_HIGH,
    VALETON_PARAM_PRE_OCTA_DRY,
    // Pitch
    VALETON_PARAM_PRE_PITCH_HIGH,
    VALETON_PARAM_PRE_PITCH_LOW,
    VALETON_PARAM_PRE_PITCH_DRY,
    VALETON_PARAM_PRE_PITCH_H_VOL,
    VALETON_PARAM_PRE_PITCH_L_VOL,
    // Detune
    VALETON_PARAM_PRE_DETUNE_DETUNE,
    VALETON_PARAM_PRE_DETUNE_WET,
    VALETON_PARAM_PRE_DETUNE_DRY,
    
    //**** Dist ****
    VALETON_PARAM_DIST_ENABLE,
    VALETON_PARAM_DIST_TYPE,    
    // Green OD
    VALETON_PARAM_DIST_GREEN_OD_GAIN,
    VALETON_PARAM_DIST_GREEN_OD_TONE,
    VALETON_PARAM_DIST_GREEN_OD_VOL,
    // Yellow OD
    VALETON_PARAM_DIST_YELLOW_OD_GAIN,
    VALETON_PARAM_DIST_YELLOW_OD_VOL,
    // Super OD
    VALETON_PARAM_DIST_SUPER_OD_GAIN,
    VALETON_PARAM_DIST_SUPER_OD_TONE,
    VALETON_PARAM_DIST_SUPER_OD_VOL,
    // SM Dist
    VALETON_PARAM_DIST_SM_DIST_GAIN,
    VALETON_PARAM_DIST_SM_DIST_TONE,
    VALETON_PARAM_DIST_SM_DIST_VOL,
    // Plustortion
    VALETON_PARAM_DIST_PLUSTORTION_GAIN,
    VALETON_PARAM_DIST_PLUSTORTION_VOL,
    // La Charger
    VALETON_PARAM_DIST_LA_CHARGER_GAIN,
    VALETON_PARAM_DIST_LA_CHARGER_TONE,
    VALETON_PARAM_DIST_LA_CHARGER_VOL,
    // Darktale
    VALETON_PARAM_DIST_DARKTALE_GAIN,
    VALETON_PARAM_DIST_DARKTALE_FILTER,
    VALETON_PARAM_DIST_DARKTALE_VOL,
    // Sora Fuzz
    VALETON_PARAM_DIST_SORA_FUZZ_FUZZ,
    VALETON_PARAM_DIST_SORA_FUZZ_VOL,
    // Red Haze
    VALETON_PARAM_DIST_RED_HAZE_FUZZ,
    VALETON_PARAM_DIST_RED_HAZE_VOL,
    // Bass OD
    VALETON_PARAM_DIST_BASS_OD_GAIN,
    VALETON_PARAM_DIST_BASS_OD_BLEND,
    VALETON_PARAM_DIST_BASS_OD_VOL,
    VALETON_PARAM_DIST_BASS_OD_BASS,
    VALETON_PARAM_DIST_BASS_OD_TREBLE,

    //**** EQ ****
    VALETON_PARAM_EQ_ENABLE,
    VALETON_PARAM_EQ_TYPE,
    // Guitar EQ 1
    VALETON_PARAM_EQ_GUITAR_EQ1_125HZ,
    VALETON_PARAM_EQ_GUITAR_EQ1_400HZ,
    VALETON_PARAM_EQ_GUITAR_EQ1_800HZ,
    VALETON_PARAM_EQ_GUITAR_EQ1_1600HZ,
    VALETON_PARAM_EQ_GUITAR_EQ1_4000HZ,
    VALETON_PARAM_EQ_GUITAR_EQ1_VOL,
    // Guitar EQ 2
    VALETON_PARAM_EQ_GUITAR_EQ2_100HZ,
    VALETON_PARAM_EQ_GUITAR_EQ2_500HZ,
    VALETON_PARAM_EQ_GUITAR_EQ2_1000HZ,
    VALETON_PARAM_EQ_GUITAR_EQ2_3000HZ,
    VALETON_PARAM_EQ_GUITAR_EQ2_6000HZ,
    VALETON_PARAM_EQ_GUITAR_EQ2_VOL,
    // Base EQ 1
    VALETON_PARAM_EQ_BASS_EQ1_33HZ,
    VALETON_PARAM_EQ_BASS_EQ1_150HZ,
    VALETON_PARAM_EQ_BASS_EQ1_600HZ,
    VALETON_PARAM_EQ_BASS_EQ1_2000HZ,
    VALETON_PARAM_EQ_BASS_EQ1_8000HZ,
    VALETON_PARAM_EQ_BASS_EQ1_VOL,
    // Base EQ 2
    VALETON_PARAM_EQ_BASS_EQ2_50HZ,
    VALETON_PARAM_EQ_BASS_EQ2_120HZ,
    VALETON_PARAM_EQ_BASS_EQ2_400HZ,
    VALETON_PARAM_EQ_BASS_EQ2_800HZ,
    VALETON_PARAM_EQ_BASS_EQ2_4500HZ,
    VALETON_PARAM_EQ_BASS_EQ2_VOL,
    // Mess EQ
    VALETON_PARAM_EQ_MESS_EQ_80HZ,
    VALETON_PARAM_EQ_MESS_EQ_240HZ,
    VALETON_PARAM_EQ_MESS_EQ_750HZ,
    VALETON_PARAM_EQ_MESS_EQ_2200HZ,
    VALETON_PARAM_EQ_MESS_EQ_6600HZ,

    //**** Mod ****
    VALETON_PARAM_MOD_ENABLE,
    VALETON_PARAM_MOD_TYPE,
    // A Chorus
    VALETON_PARAM_MOD_A_CHORUS_DEPTH,
    VALETON_PARAM_MOD_A_CHORUS_RATE,
    VALETON_PARAM_MOD_A_CHORUS_TONE,
    // B Chorus
    VALETON_PARAM_MOD_B_CHORUS_DEPTH,
    VALETON_PARAM_MOD_B_CHORUS_RATE,
    VALETON_PARAM_MOD_B_CHORUS_VOL,
    // Jet
    VALETON_PARAM_MOD_JET_DEPTH,
    VALETON_PARAM_MOD_JET_RATE,
    VALETON_PARAM_MOD_JET_PDELAY,
    VALETON_PARAM_MOD_JET_FBACK,
    // N-Jet
    VALETON_PARAM_MOD_N_JET_DEPTH,
    VALETON_PARAM_MOD_N_JET_RATE,
    VALETON_PARAM_MOD_N_JET_PDELAY,
    VALETON_PARAM_MOD_N_JET_FBACK,
    // O-Phase
    VALETON_PARAM_MOD_O_PHASE_RATE,
    // M-Vibe
    VALETON_PARAM_MOD_M_VIBE_DEPTH,
    VALETON_PARAM_MOD_M_VIBE_RATE,
    // V-Roto
    VALETON_PARAM_MOD_V_ROTO_DEPTH,
    VALETON_PARAM_MOD_V_ROTO_RATE,
    // Vibrato
    VALETON_PARAM_MOD_VIBRATO_DEPTH,
    VALETON_PARAM_MOD_VIBRATO_RATE,
    VALETON_PARAM_MOD_VIBRATO_VOL,
    // O-Trem
    VALETON_PARAM_MOD_O_TREM_DEPTH,
    VALETON_PARAM_MOD_O_TREM_RATE,
    // Sine Trem
    VALETON_PARAM_MOD_SINE_TREM_DEPTH,
    VALETON_PARAM_MOD_SINE_TREM_RATE,
    VALETON_PARAM_MOD_SINE_TREM_VOL,
    // Bias Trem
    VALETON_PARAM_MOD_BIAS_TREM_DEPTH,
    VALETON_PARAM_MOD_BIAS_TREM_RATE,
    VALETON_PARAM_MOD_BIAS_TREM_VOL,
    VALETON_PARAM_MOD_BIAS_TREM_BIAS,

    //**** Delay ****
    VALETON_PARAM_DLY_ENABLE,
    VALETON_PARAM_DLY_TYPE,
    // Pure
    VALETON_PARAM_DLY_PURE_MIX,
    VALETON_PARAM_DLY_PURE_TIME,
    VALETON_PARAM_DLY_PURE_FEEDBACK,
    VALETON_PARAM_DLY_PURE_TRAIL,
    // Analog
    VALETON_PARAM_DLY_ANALOG_MIX,
    VALETON_PARAM_DLY_ANALOG_TIME,
    VALETON_PARAM_DLY_ANALOG_FEEDBACK,
    VALETON_PARAM_DLY_ANALOG_TRAIL,
    // Slapback
    VALETON_PARAM_DLY_SLAPBACK_MIX,
    VALETON_PARAM_DLY_SLAPBACK_TIME,
    VALETON_PARAM_DLY_SLAPBACK_FEEDBACK,
    VALETON_PARAM_DLY_SLAPBACK_TRAIL,
    // Sweet Echo
    VALETON_PARAM_DLY_SWEET_ECHO_MIX,
    VALETON_PARAM_DLY_SWEET_ECHO_TIME,
    VALETON_PARAM_DLY_SWEET_ECHO_FEEDBACK,
    VALETON_PARAM_DLY_SWEET_ECHO_TRAIL,
    // Tape
    VALETON_PARAM_DLY_TAPE_MIX,
    VALETON_PARAM_DLY_TAPE_TIME,
    VALETON_PARAM_DLY_TAPE_FEEDBACK,
    VALETON_PARAM_DLY_TAPE_TRAIL,
    // Tube
    VALETON_PARAM_DLY_TUBE_MIX,
    VALETON_PARAM_DLY_TUBE_TIME,
    VALETON_PARAM_DLY_TUBE_FEEDBACK,
    VALETON_PARAM_DLY_TUBE_TRAIL,
    // Rev Echo
    VALETON_PARAM_DLY_REV_ECHO_MIX,
    VALETON_PARAM_DLY_REV_ECHO_TIME,
    VALETON_PARAM_DLY_REV_ECHO_FEEDBACK,
    VALETON_PARAM_DLY_REV_ECHO_TRAIL,
    // Ring Echo
    VALETON_PARAM_DLY_RING_ECHO_MIX,
    VALETON_PARAM_DLY_RING_ECHO_TIME,
    VALETON_PARAM_DLY_RING_ECHO_FEEDBACK,
    VALETON_PARAM_DLY_RING_ECHO_R_MIX,
    VALETON_PARAM_DLY_RING_ECHO_FREQ,
    VALETON_PARAM_DLY_RING_ECHO_TONE,
    VALETON_PARAM_DLY_RING_ECHO_TRAIL,
    // Sweep Echo
    VALETON_PARAM_DLY_SWEEP_ECHO_MIX,
    VALETON_PARAM_DLY_SWEEP_ECHO_TIME,
    VALETON_PARAM_DLY_SWEEP_ECHO_FBACK,
    VALETON_PARAM_DLY_SWEEP_ECHO_S_DEPTH,
    VALETON_PARAM_DLY_SWEEP_ECHO_S_RATE,
    VALETON_PARAM_DLY_SWEEP_ECHO_TRAIL,
    // Ping Pong
    VALETON_PARAM_DLY_PING_PONG_MIX,
    VALETON_PARAM_DLY_PING_PONG_TIME,
    VALETON_PARAM_DLY_PING_PONG_FEEDBACK,
    VALETON_PARAM_DLY_PING_PONG_TRAIL,

    //**** Reverb ****
    VALETON_PARAM_RVB_ENABLE,
    VALETON_PARAM_RVB_TYPE,
    // Air
    VALETON_PARAM_RVB_AIR_MIX,
    VALETON_PARAM_RVB_AIR_DECAY,
    VALETON_PARAM_RVB_AIR_DAMP,
    VALETON_PARAM_RVB_AIR_TRAIL,
    // Room
    VALETON_PARAM_RVB_ROOM_MIX,
    VALETON_PARAM_RVB_ROOM_DECAY,
    VALETON_PARAM_RVB_ROOM_TRAIL,
    // Hall
    VALETON_PARAM_RVB_HALL_MIX,
    VALETON_PARAM_RVB_HALL_DECAY,
    VALETON_PARAM_RVB_HALL_TRAIL,
    // Church
    VALETON_PARAM_RVB_CHURCH_MIX,
    VALETON_PARAM_RVB_CHURCH_DECAY,
    VALETON_PARAM_RVB_CHURCH_TRAIL,
    // Plate L
    VALETON_PARAM_RVB_PLATE_L_MIX,
    VALETON_PARAM_RVB_PLATE_L_DECAY,
    VALETON_PARAM_RVB_PLATE_L_TRAIL,
    // Plate
    VALETON_PARAM_RVB_PLATE_MIX,
    VALETON_PARAM_RVB_PLATE_DECAY,
    VALETON_PARAM_RVB_PLATE_DAMP,
    VALETON_PARAM_RVB_PLATE_TRAIL,
    // Spring
    VALETON_PARAM_RVB_SPRING_MIX,
    VALETON_PARAM_RVB_SPRING_DECAY,
    VALETON_PARAM_RVB_SPRING_TRAIL,
    // N-Star
    VALETON_PARAM_RVB_N_STAR_MIX,
    VALETON_PARAM_RVB_N_STAR_DECAY,
    VALETON_PARAM_RVB_N_STAR_TRAIL,
    // Deepsea
    VALETON_PARAM_RVB_DEEPSEA_MIX,
    VALETON_PARAM_RVB_DEEPSEA_DECAY,
    VALETON_PARAM_RVB_DEEPSEA_TRAIL,
    // Sweet Space
    VALETON_PARAM_RVB_SWEET_SPACE_MIX,
    VALETON_PARAM_RVB_SWEET_SPACE_DECAY,
    VALETON_PARAM_RVB_SWEET_SPACE_DAMP,
    VALETON_PARAM_RVB_SWEET_SPACE_MOD,
    VALETON_PARAM_RVB_SWEET_SPACE_TRAIL,

    // must be last actual parameter
    VALETON_PARAM_LAST,

    // these are not parameters as such, but globals/special/set differently to the params above
    VALETON_GLOBAL_BPM,
    VALETON_GLOBAL_INPUT_TRIM,
    VALETON_GLOBAL_CABSIM_BYPASS,
    VALETON_GLOBAL_TUNING_REFERENCE,
    VALETON_GLOBAL_BYPASS,          
    VALETON_GLOBAL_MASTER_VOLUME, 

    // must be last actual global
    VALETON_GLOBAL_LAST
};

// special cases for handling effect switches that use Midi but don't change a parameter
#define VALETON_UNKNOWN           0xFFFF


esp_err_t valeton_params_init(void);
esp_err_t valeton_params_get_locked_access(tModellerParameter** param_ptr);
esp_err_t valeton_params_release_locked_access(void);
esp_err_t valeton_params_get_min_max(uint16_t param_index, float* min, float* max);
esp_err_t valeton_dump_parameters(void);
float valeton_params_clamp_value(uint16_t param_index, float value);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif