// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Tonex_Controller

#include "../ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsPanel = lv_obj_create(ui_Settings);
    lv_obj_set_width(ui_SettingsPanel, 798);
    lv_obj_set_height(ui_SettingsPanel, 414);
    lv_obj_set_x(ui_SettingsPanel, 0);
    lv_obj_set_y(ui_SettingsPanel, 31);
    lv_obj_set_align(ui_SettingsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SettingsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingsPanel, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SettingsPanel, lv_color_hex(0x563F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SettingsPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsPanel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SettingsPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchRow1 = lv_obj_create(ui_SettingsPanel);
    lv_obj_remove_style_all(ui_SwitchRow1);
    lv_obj_set_width(ui_SwitchRow1, 785);
    lv_obj_set_height(ui_SwitchRow1, 45);
    lv_obj_set_x(ui_SwitchRow1, -82);
    lv_obj_set_y(ui_SwitchRow1, 1);
    lv_obj_set_align(ui_SwitchRow1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SwitchRow1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SwitchRow1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SwitchRow1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1Group = lv_obj_create(ui_SwitchRow1);
    lv_obj_remove_style_all(ui_Switch1Group);
    lv_obj_set_width(ui_Switch1Group, 257);
    lv_obj_set_height(ui_Switch1Group, 50);
    lv_obj_set_align(ui_Switch1Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Switch1Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1Label = lv_label_create(ui_Switch1Group);
    lv_obj_set_width(ui_Switch1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Switch1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Switch1Label, 6);
    lv_obj_set_y(ui_Switch1Label, 0);
    lv_obj_set_align(ui_Switch1Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Switch1Label, "Switch 1");
    lv_obj_set_style_text_font(ui_Switch1Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Switch1Group);
    lv_obj_set_width(ui_Switch1, 80);
    lv_obj_set_height(ui_Switch1, 35);
    lv_obj_set_x(ui_Switch1, 156);
    lv_obj_set_y(ui_Switch1, 0);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_LEFT_MID);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x674D35), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Switch2Group = lv_obj_create(ui_SwitchRow1);
    lv_obj_remove_style_all(ui_Switch2Group);
    lv_obj_set_width(ui_Switch2Group, 257);
    lv_obj_set_height(ui_Switch2Group, 50);
    lv_obj_set_align(ui_Switch2Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Switch2Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch2Label = lv_label_create(ui_Switch2Group);
    lv_obj_set_width(ui_Switch2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Switch2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Switch2Label, 10);
    lv_obj_set_y(ui_Switch2Label, 0);
    lv_obj_set_align(ui_Switch2Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Switch2Label, "Switch 2");
    lv_obj_set_style_text_font(ui_Switch2Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Switch2Group);
    lv_obj_set_width(ui_Switch2, 80);
    lv_obj_set_height(ui_Switch2, 35);
    lv_obj_set_x(ui_Switch2, 165);
    lv_obj_set_y(ui_Switch2, 0);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_LEFT_MID);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x674D35), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_SwitchRow2 = lv_obj_create(ui_SettingsPanel);
    lv_obj_remove_style_all(ui_SwitchRow2);
    lv_obj_set_width(ui_SwitchRow2, 785);
    lv_obj_set_height(ui_SwitchRow2, 45);
    lv_obj_set_align(ui_SwitchRow2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SwitchRow2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SwitchRow2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_SwitchRow2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch3Group = lv_obj_create(ui_SwitchRow2);
    lv_obj_remove_style_all(ui_Switch3Group);
    lv_obj_set_width(ui_Switch3Group, 257);
    lv_obj_set_height(ui_Switch3Group, 50);
    lv_obj_set_align(ui_Switch3Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Switch3Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch3Label = lv_label_create(ui_Switch3Group);
    lv_obj_set_width(ui_Switch3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Switch3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Switch3Label, 6);
    lv_obj_set_y(ui_Switch3Label, 0);
    lv_obj_set_align(ui_Switch3Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Switch3Label, "Switch 3");
    lv_obj_set_style_text_font(ui_Switch3Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Switch3Group);
    lv_obj_set_width(ui_Switch3, 80);
    lv_obj_set_height(ui_Switch3, 35);
    lv_obj_set_x(ui_Switch3, 156);
    lv_obj_set_y(ui_Switch3, 0);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_LEFT_MID);

    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x674D35), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_Switch4Group = lv_obj_create(ui_SwitchRow2);
    lv_obj_remove_style_all(ui_Switch4Group);
    lv_obj_set_width(ui_Switch4Group, 257);
    lv_obj_set_height(ui_Switch4Group, 50);
    lv_obj_set_align(ui_Switch4Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Switch4Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch4Label = lv_label_create(ui_Switch4Group);
    lv_obj_set_width(ui_Switch4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Switch4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Switch4Label, 10);
    lv_obj_set_y(ui_Switch4Label, 0);
    lv_obj_set_align(ui_Switch4Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Switch4Label, "Switch 4");
    lv_obj_set_style_text_font(ui_Switch4Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch4 = lv_switch_create(ui_Switch4Group);
    lv_obj_set_width(ui_Switch4, 80);
    lv_obj_set_height(ui_Switch4, 35);
    lv_obj_set_x(ui_Switch4, 165);
    lv_obj_set_y(ui_Switch4, 0);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_LEFT_MID);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0x674D35), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Switch4, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch4, 255, LV_PART_KNOB | LV_STATE_CHECKED);

    ui_SelectGroup = lv_obj_create(ui_SettingsPanel);
    lv_obj_remove_style_all(ui_SelectGroup);
    lv_obj_set_width(ui_SelectGroup, 373);
    lv_obj_set_height(ui_SelectGroup, 50);
    lv_obj_set_x(ui_SelectGroup, -202);
    lv_obj_set_y(ui_SelectGroup, -111);
    lv_obj_set_align(ui_SelectGroup, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SelectGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Select1Label = lv_label_create(ui_SelectGroup);
    lv_obj_set_width(ui_Select1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Select1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Select1Label, 6);
    lv_obj_set_y(ui_Select1Label, 0);
    lv_obj_set_align(ui_Select1Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Select1Label, "Model");
    lv_obj_set_style_text_font(ui_Select1Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Select1 = lv_dropdown_create(ui_SelectGroup);
    lv_dropdown_set_options(ui_Select1, "Spring 1\nSpring 2\nSpring 3\nSpring 4\nRoom\nPlate");
    lv_obj_set_width(ui_Select1, 202);
    lv_obj_set_height(ui_Select1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Select1, 80);
    lv_obj_set_y(ui_Select1, 0);
    lv_obj_set_align(ui_Select1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Select1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Select1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Select1, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Select1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Select1, lv_color_hex(0x454545), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Select1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Select1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Select1), &lv_font_montserrat_24,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Select1), lv_color_hex(0x1F1F1F),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Select1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Select1), lv_color_hex(0x513D2B),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Select1), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Select1), lv_color_hex(0xFB9230),
                                LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Select1), 255,  LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Select1), lv_color_hex(0x513D2B),
                              LV_PART_SELECTED | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Select1), 255,  LV_PART_SELECTED | LV_STATE_CHECKED);

    ui_Slider1Group = lv_obj_create(ui_SettingsPanel);
    lv_obj_remove_style_all(ui_Slider1Group);
    lv_obj_set_width(ui_Slider1Group, 785);
    lv_obj_set_height(ui_Slider1Group, 40);
    lv_obj_set_x(ui_Slider1Group, 0);
    lv_obj_set_y(ui_Slider1Group, -128);
    lv_obj_set_align(ui_Slider1Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slider1Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider1Label = lv_label_create(ui_Slider1Group);
    lv_obj_set_width(ui_Slider1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider1Label, 6);
    lv_obj_set_y(ui_Slider1Label, 0);
    lv_obj_set_align(ui_Slider1Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider1Label, "Label");
    lv_obj_set_style_text_font(ui_Slider1Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Slider1Group);
    lv_slider_set_range(ui_Slider1, 0, 10);
    lv_slider_set_value(ui_Slider1, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 500);
    lv_obj_set_height(ui_Slider1, 20);
    lv_obj_set_x(ui_Slider1, 188);
    lv_obj_set_y(ui_Slider1, 0);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider1Value = lv_label_create(ui_Slider1Group);
    lv_obj_set_width(ui_Slider1Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider1Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider1Value, 704);
    lv_obj_set_y(ui_Slider1Value, 0);
    lv_obj_set_align(ui_Slider1Value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider1Value, "0");
    lv_obj_set_style_text_font(ui_Slider1Value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2Group = lv_obj_create(ui_SettingsPanel);
    lv_obj_remove_style_all(ui_Slider2Group);
    lv_obj_set_width(ui_Slider2Group, 785);
    lv_obj_set_height(ui_Slider2Group, 40);
    lv_obj_set_x(ui_Slider2Group, 0);
    lv_obj_set_y(ui_Slider2Group, -79);
    lv_obj_set_align(ui_Slider2Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slider2Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider2Label = lv_label_create(ui_Slider2Group);
    lv_obj_set_width(ui_Slider2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider2Label, 6);
    lv_obj_set_y(ui_Slider2Label, 0);
    lv_obj_set_align(ui_Slider2Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider2Label, "Label");
    lv_obj_set_style_text_font(ui_Slider2Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Slider2Group);
    lv_slider_set_range(ui_Slider2, 0, 10);
    lv_slider_set_value(ui_Slider2, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 500);
    lv_obj_set_height(ui_Slider2, 20);
    lv_obj_set_x(ui_Slider2, 188);
    lv_obj_set_y(ui_Slider2, 0);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider2Value = lv_label_create(ui_Slider2Group);
    lv_obj_set_width(ui_Slider2Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider2Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider2Value, 704);
    lv_obj_set_y(ui_Slider2Value, 0);
    lv_obj_set_align(ui_Slider2Value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider2Value, "0");
    lv_obj_set_style_text_font(ui_Slider2Value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider3Group = lv_obj_create(ui_SettingsPanel);
    lv_obj_remove_style_all(ui_Slider3Group);
    lv_obj_set_width(ui_Slider3Group, 785);
    lv_obj_set_height(ui_Slider3Group, 40);
    lv_obj_set_x(ui_Slider3Group, 0);
    lv_obj_set_y(ui_Slider3Group, -39);
    lv_obj_set_align(ui_Slider3Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slider3Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider3Label = lv_label_create(ui_Slider3Group);
    lv_obj_set_width(ui_Slider3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider3Label, 6);
    lv_obj_set_y(ui_Slider3Label, 0);
    lv_obj_set_align(ui_Slider3Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider3Label, "Label");
    lv_obj_set_style_text_font(ui_Slider3Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider3 = lv_slider_create(ui_Slider3Group);
    lv_slider_set_range(ui_Slider3, 0, 10);
    lv_slider_set_value(ui_Slider3, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 500);
    lv_obj_set_height(ui_Slider3, 20);
    lv_obj_set_x(ui_Slider3, 188);
    lv_obj_set_y(ui_Slider3, 0);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider3, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider3, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider3Value = lv_label_create(ui_Slider3Group);
    lv_obj_set_width(ui_Slider3Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider3Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider3Value, 704);
    lv_obj_set_y(ui_Slider3Value, 0);
    lv_obj_set_align(ui_Slider3Value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider3Value, "0");
    lv_obj_set_style_text_font(ui_Slider3Value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider4Group = lv_obj_create(ui_SettingsPanel);
    lv_obj_remove_style_all(ui_Slider4Group);
    lv_obj_set_width(ui_Slider4Group, 785);
    lv_obj_set_height(ui_Slider4Group, 40);
    lv_obj_set_x(ui_Slider4Group, 0);
    lv_obj_set_y(ui_Slider4Group, 14);
    lv_obj_set_align(ui_Slider4Group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slider4Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider4Label = lv_label_create(ui_Slider4Group);
    lv_obj_set_width(ui_Slider4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider4Label, 6);
    lv_obj_set_y(ui_Slider4Label, 0);
    lv_obj_set_align(ui_Slider4Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider4Label, "Label");
    lv_obj_set_style_text_font(ui_Slider4Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider4 = lv_slider_create(ui_Slider4Group);
    lv_slider_set_range(ui_Slider4, 0, 10);
    lv_slider_set_value(ui_Slider4, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 500);
    lv_obj_set_height(ui_Slider4, 20);
    lv_obj_set_x(ui_Slider4, 188);
    lv_obj_set_y(ui_Slider4, 0);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider4, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider4, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider4Value = lv_label_create(ui_Slider4Group);
    lv_obj_set_width(ui_Slider4Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider4Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider4Value, 704);
    lv_obj_set_y(ui_Slider4Value, 0);
    lv_obj_set_align(ui_Slider4Value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider4Value, "0");
    lv_obj_set_style_text_font(ui_Slider4Value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider5Group = lv_obj_create(ui_SettingsPanel);
    lv_obj_remove_style_all(ui_Slider5Group);
    lv_obj_set_width(ui_Slider5Group, 785);
    lv_obj_set_height(ui_Slider5Group, 40);
    lv_obj_set_x(ui_Slider5Group, -1);
    lv_obj_set_y(ui_Slider5Group, 69);
    lv_obj_set_align(ui_Slider5Group, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider5Group, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Slider5Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider5Label = lv_label_create(ui_Slider5Group);
    lv_obj_set_width(ui_Slider5Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider5Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider5Label, 6);
    lv_obj_set_y(ui_Slider5Label, 0);
    lv_obj_set_align(ui_Slider5Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider5Label, "Label");
    lv_obj_set_style_text_font(ui_Slider5Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider5 = lv_slider_create(ui_Slider5Group);
    lv_slider_set_range(ui_Slider5, 0, 10);
    lv_slider_set_value(ui_Slider5, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider5) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider5, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider5, 500);
    lv_obj_set_height(ui_Slider5, 20);
    lv_obj_set_x(ui_Slider5, 188);
    lv_obj_set_y(ui_Slider5, 0);
    lv_obj_set_align(ui_Slider5, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_Slider5, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider5, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider5, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider5, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider5Value = lv_label_create(ui_Slider5Group);
    lv_obj_set_width(ui_Slider5Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider5Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider5Value, 704);
    lv_obj_set_y(ui_Slider5Value, 0);
    lv_obj_set_align(ui_Slider5Value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider5Value, "0");
    lv_obj_set_style_text_font(ui_Slider5Value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider6Group = lv_obj_create(ui_SettingsPanel);
    lv_obj_remove_style_all(ui_Slider6Group);
    lv_obj_set_width(ui_Slider6Group, 785);
    lv_obj_set_height(ui_Slider6Group, 40);
    lv_obj_set_x(ui_Slider6Group, 0);
    lv_obj_set_y(ui_Slider6Group, 125);
    lv_obj_set_align(ui_Slider6Group, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider6Group, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Slider6Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider6Label = lv_label_create(ui_Slider6Group);
    lv_obj_set_width(ui_Slider6Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider6Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider6Label, 6);
    lv_obj_set_y(ui_Slider6Label, 0);
    lv_obj_set_align(ui_Slider6Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider6Label, "Label");
    lv_obj_set_style_text_font(ui_Slider6Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider6 = lv_slider_create(ui_Slider6Group);
    lv_slider_set_range(ui_Slider6, 0, 10);
    lv_slider_set_value(ui_Slider6, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider6) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider6, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider6, 500);
    lv_obj_set_height(ui_Slider6, 20);
    lv_obj_set_x(ui_Slider6, 188);
    lv_obj_set_y(ui_Slider6, 0);
    lv_obj_set_align(ui_Slider6, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_Slider6, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider6, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider6, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider6, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider6, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider6Value = lv_label_create(ui_Slider6Group);
    lv_obj_set_width(ui_Slider6Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider6Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider6Value, 704);
    lv_obj_set_y(ui_Slider6Value, 0);
    lv_obj_set_align(ui_Slider6Value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider6Value, "0");
    lv_obj_set_style_text_font(ui_Slider6Value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider7Group = lv_obj_create(ui_SettingsPanel);
    lv_obj_remove_style_all(ui_Slider7Group);
    lv_obj_set_width(ui_Slider7Group, 785);
    lv_obj_set_height(ui_Slider7Group, 40);
    lv_obj_set_x(ui_Slider7Group, 2);
    lv_obj_set_y(ui_Slider7Group, 181);
    lv_obj_set_align(ui_Slider7Group, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slider7Group, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Slider7Group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Slider7Label = lv_label_create(ui_Slider7Group);
    lv_obj_set_width(ui_Slider7Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider7Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider7Label, 6);
    lv_obj_set_y(ui_Slider7Label, 0);
    lv_obj_set_align(ui_Slider7Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider7Label, "Label");
    lv_obj_set_style_text_font(ui_Slider7Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider7 = lv_slider_create(ui_Slider7Group);
    lv_slider_set_range(ui_Slider7, 0, 10);
    lv_slider_set_value(ui_Slider7, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider7) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider7, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider7, 500);
    lv_obj_set_height(ui_Slider7, 20);
    lv_obj_set_x(ui_Slider7, 188);
    lv_obj_set_y(ui_Slider7, 0);
    lv_obj_set_align(ui_Slider7, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_Slider7, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider7, lv_color_hex(0x513D2B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider7, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider7, lv_color_hex(0xFB9230), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider7, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider7Value = lv_label_create(ui_Slider7Group);
    lv_obj_set_width(ui_Slider7Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider7Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider7Value, 704);
    lv_obj_set_y(ui_Slider7Value, 0);
    lv_obj_set_align(ui_Slider7Value, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Slider7Value, "0");
    lv_obj_set_style_text_font(ui_Slider7Value, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsTabview = lv_tabview_create(ui_Settings, LV_DIR_TOP, 60);
    lv_obj_set_width(ui_SettingsTabview, 798);
    lv_obj_set_height(ui_SettingsTabview, 61);
    lv_obj_set_x(ui_SettingsTabview, 0);
    lv_obj_set_y(ui_SettingsTabview, -208);
    lv_obj_set_align(ui_SettingsTabview, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingsTabview,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_SettingsTabview, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsTabview, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SettingsTabview, lv_color_hex(0x563F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SettingsTabview, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SettingsTabview, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SettingsTabview, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsTabview, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_SettingsTabview), &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_SettingsTabview), lv_color_hex(0x2A2A2A),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_SettingsTabview), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_SettingsTabview), lv_color_hex(0xC0C0C0),
                                LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_SettingsTabview), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_SettingsTabview), lv_color_hex(0x373737),
                                  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_SettingsTabview), 255,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_SettingsTabview), 2,  LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_SettingsTabview), LV_BORDER_SIDE_LEFT,
                                 LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_SettingsTabview), lv_color_hex(0xFB9230),
                                LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_SettingsTabview), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_SettingsTabview), lv_color_hex(0x513D2B),
                              LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_SettingsTabview), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_SettingsTabview), lv_color_hex(0xFB9230),
                                  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_SettingsTabview), 255,  LV_PART_ITEMS | LV_STATE_CHECKED);

    ui_NoiseGateTab = lv_tabview_add_tab(ui_SettingsTabview, "Gate");
    lv_obj_clear_flag(ui_NoiseGateTab, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_CompressorTab = lv_tabview_add_tab(ui_SettingsTabview, "Comp");
    lv_obj_clear_flag(ui_CompressorTab, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_EQTab = lv_tabview_add_tab(ui_SettingsTabview, "EQ");
    lv_obj_clear_flag(ui_EQTab, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_ReverbPage = lv_tabview_add_tab(ui_SettingsTabview, "Rev");
    lv_obj_clear_flag(ui_ReverbPage, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Modulation = lv_tabview_add_tab(ui_SettingsTabview, "Mod");
    lv_obj_clear_flag(ui_Modulation, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Delay = lv_tabview_add_tab(ui_SettingsTabview, "Dly");
    lv_obj_clear_flag(ui_Delay, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Amplifier = lv_tabview_add_tab(ui_SettingsTabview, "Amp");
    lv_obj_clear_flag(ui_Amplifier, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Global = lv_tabview_add_tab(ui_SettingsTabview, "Glob");
    lv_obj_clear_flag(ui_Global, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Exit = lv_tabview_add_tab(ui_SettingsTabview, "Exit");

    ui_CloseImage = lv_img_create(ui_Settings);
    lv_img_set_src(ui_CloseImage, &ui_img_tick_png);
    lv_obj_set_width(ui_CloseImage, 86);
    lv_obj_set_height(ui_CloseImage, 62);
    lv_obj_set_x(ui_CloseImage, 360);
    lv_obj_set_y(ui_CloseImage, -148);
    lv_obj_set_align(ui_CloseImage, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_CloseImage, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_CloseImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_CloseImage, 160);

    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch3, ui_event_Switch3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Select1, ui_event_Select1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider4, ui_event_Slider4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider5, ui_event_Slider5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider6, ui_event_Slider6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider7, ui_event_Slider7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsTabview, ui_event_SettingsTabview, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CloseImage, ui_event_CloseImage, LV_EVENT_ALL, NULL);

}
