// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Tonex_Controller_480x320land

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BottomPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BottomPanel, 480);
    lv_obj_set_height(ui_BottomPanel, 53);
    lv_obj_set_x(ui_BottomPanel, 0);
    lv_obj_set_y(ui_BottomPanel, 133);
    lv_obj_set_align(ui_BottomPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BottomPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BottomPanel, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BottomPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_BottomPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_BottomPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_BottomPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PreviousContainer = lv_obj_create(ui_BottomPanel);
    lv_obj_remove_style_all(ui_PreviousContainer);
    lv_obj_set_width(ui_PreviousContainer, 45);
    lv_obj_set_height(ui_PreviousContainer, 44);
    lv_obj_set_x(ui_PreviousContainer, -212);
    lv_obj_set_y(ui_PreviousContainer, 0);
    lv_obj_set_align(ui_PreviousContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PreviousContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PreviousButton = lv_imgbtn_create(ui_PreviousContainer);
    lv_imgbtn_set_src(ui_PreviousButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_previous_png, NULL);
    lv_imgbtn_set_src(ui_PreviousButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_previous_down_png, NULL);
    lv_obj_set_height(ui_PreviousButton, 44);
    lv_obj_set_width(ui_PreviousButton, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_x(ui_PreviousButton, 6);
    lv_obj_set_y(ui_PreviousButton, 5);
    lv_obj_set_align(ui_PreviousButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PreviousButton, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_PreviousButton, 192, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NextContainer = lv_obj_create(ui_BottomPanel);
    lv_obj_remove_style_all(ui_NextContainer);
    lv_obj_set_width(ui_NextContainer, 45);
    lv_obj_set_height(ui_NextContainer, 45);
    lv_obj_set_x(ui_NextContainer, 211);
    lv_obj_set_y(ui_NextContainer, -1);
    lv_obj_set_align(ui_NextContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NextContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NextButton = lv_imgbtn_create(ui_NextContainer);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_next_png, NULL);
    lv_imgbtn_set_src(ui_NextButton, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_next_down_png, NULL);
    lv_obj_set_height(ui_NextButton, 51);
    lv_obj_set_width(ui_NextButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_NextButton, 7);
    lv_obj_set_y(ui_NextButton, 8);
    lv_obj_set_align(ui_NextButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_NextButton, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_transform_zoom(ui_NextButton, 192, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IconEQ = lv_img_create(ui_BottomPanel);
    lv_img_set_src(ui_IconEQ, &ui_img_effect_icon_eq_png);
    lv_obj_set_width(ui_IconEQ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconEQ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IconEQ, -168);
    lv_obj_set_y(ui_IconEQ, 0);
    lv_obj_set_align(ui_IconEQ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconEQ, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconEQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IconEQ, 192);

    ui_IconGate = lv_img_create(ui_BottomPanel);
    lv_img_set_src(ui_IconGate, &ui_img_effect_icon_gate_off_png);
    lv_obj_set_width(ui_IconGate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconGate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IconGate, -125);
    lv_obj_set_y(ui_IconGate, 0);
    lv_obj_set_align(ui_IconGate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconGate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconGate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IconGate, 192);

    ui_IconAmp = lv_img_create(ui_BottomPanel);
    lv_img_set_src(ui_IconAmp, &ui_img_effect_icon_amp_off_png);
    lv_obj_set_width(ui_IconAmp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconAmp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IconAmp, -80);
    lv_obj_set_y(ui_IconAmp, 0);
    lv_obj_set_align(ui_IconAmp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconAmp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconAmp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IconAmp, 192);

    ui_IconCab = lv_img_create(ui_BottomPanel);
    lv_img_set_src(ui_IconCab, &ui_img_effect_icon_cab_off_png);
    lv_obj_set_width(ui_IconCab, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconCab, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IconCab, -37);
    lv_obj_set_y(ui_IconCab, 0);
    lv_obj_set_align(ui_IconCab, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconCab, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconCab, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IconCab, 192);

    ui_IconComp = lv_img_create(ui_BottomPanel);
    lv_img_set_src(ui_IconComp, &ui_img_effect_icon_comp_off_png);
    lv_obj_set_width(ui_IconComp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconComp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IconComp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconComp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconComp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IconComp, 192);

    ui_IconMod = lv_img_create(ui_BottomPanel);
    lv_img_set_src(ui_IconMod, &ui_img_effect_icon_mod_off_png);
    lv_obj_set_width(ui_IconMod, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconMod, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IconMod, 42);
    lv_obj_set_y(ui_IconMod, 0);
    lv_obj_set_align(ui_IconMod, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconMod, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconMod, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IconMod, 192);

    ui_IconDelay = lv_img_create(ui_BottomPanel);
    lv_img_set_src(ui_IconDelay, &ui_img_effect_icon_delay_off_png);
    lv_obj_set_width(ui_IconDelay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconDelay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IconDelay, 85);
    lv_obj_set_y(ui_IconDelay, 0);
    lv_obj_set_align(ui_IconDelay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconDelay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconDelay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IconDelay, 192);

    ui_IconReverb = lv_img_create(ui_BottomPanel);
    lv_img_set_src(ui_IconReverb, &ui_img_effect_icon_reverb_off_png);
    lv_obj_set_width(ui_IconReverb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IconReverb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IconReverb, 127);
    lv_obj_set_y(ui_IconReverb, 0);
    lv_obj_set_align(ui_IconReverb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IconReverb, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IconReverb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IconReverb, 192);

    ui_SettingsImage = lv_img_create(ui_BottomPanel);
    lv_img_set_src(ui_SettingsImage, &ui_img_settings_png);
    lv_obj_set_width(ui_SettingsImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsImage, 169);
    lv_obj_set_y(ui_SettingsImage, 0);
    lv_obj_set_align(ui_SettingsImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsImage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingsImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SettingsImage, 192);

    ui_TopPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TopPanel, 480);
    lv_obj_set_height(ui_TopPanel, 39);
    lv_obj_set_x(ui_TopPanel, 0);
    lv_obj_set_y(ui_TopPanel, -141);
    lv_obj_set_align(ui_TopPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TopPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TopPanel, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TopPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TopPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_TopPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IKLogo = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_IKLogo, &ui_img_smythbuilt_png);
    lv_obj_set_width(ui_IKLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IKLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IKLogo, -184);
    lv_obj_set_y(ui_IKLogo, 0);
    lv_obj_set_align(ui_IKLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IKLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IKLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_IKLogo, 192);

    ui_BTStatusConn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_BTStatusConn, &ui_img_bt_conn_png);
    lv_obj_set_width(ui_BTStatusConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTStatusConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTStatusConn, 167);
    lv_obj_set_y(ui_BTStatusConn, 0);
    lv_obj_set_align(ui_BTStatusConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTStatusConn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTStatusConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTStatusConn, 192);

    ui_BTStatusDisconn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_BTStatusDisconn, &ui_img_bt_disconn_png);
    lv_obj_set_width(ui_BTStatusDisconn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTStatusDisconn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTStatusDisconn, 167);
    lv_obj_set_y(ui_BTStatusDisconn, 0);
    lv_obj_set_align(ui_BTStatusDisconn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BTStatusDisconn, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BTStatusDisconn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BTStatusDisconn, 192);

    ui_USBStatusOK = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_USBStatusOK, &ui_img_usb_ok_png);
    lv_obj_set_width(ui_USBStatusOK, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_USBStatusOK, LV_SIZE_CONTENT);    /// 77
    lv_obj_set_x(ui_USBStatusOK, 206);
    lv_obj_set_y(ui_USBStatusOK, 0);
    lv_obj_set_align(ui_USBStatusOK, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_USBStatusOK, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_USBStatusOK, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_USBStatusOK, 192);

    ui_USBStatusFail = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_USBStatusFail, &ui_img_usb_fail_png);
    lv_obj_set_width(ui_USBStatusFail, LV_SIZE_CONTENT);   /// 91
    lv_obj_set_height(ui_USBStatusFail, LV_SIZE_CONTENT);    /// 77
    lv_obj_set_x(ui_USBStatusFail, 206);
    lv_obj_set_y(ui_USBStatusFail, 0);
    lv_obj_set_align(ui_USBStatusFail, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_USBStatusFail, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_USBStatusFail, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_USBStatusFail, 192);

    ui_WiFiStatusConn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_WiFiStatusConn, &ui_img_wifi_conn_png);
    lv_obj_set_width(ui_WiFiStatusConn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiStatusConn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiStatusConn, 132);
    lv_obj_set_y(ui_WiFiStatusConn, 0);
    lv_obj_set_align(ui_WiFiStatusConn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiStatusConn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiStatusConn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WiFiStatusConn, 192);

    ui_WiFiStatusDisconn = lv_img_create(ui_TopPanel);
    lv_img_set_src(ui_WiFiStatusDisconn, &ui_img_wifi_disconn_png);
    lv_obj_set_width(ui_WiFiStatusDisconn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiStatusDisconn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiStatusDisconn, 132);
    lv_obj_set_y(ui_WiFiStatusDisconn, 0);
    lv_obj_set_align(ui_WiFiStatusDisconn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiStatusDisconn, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WiFiStatusDisconn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WiFiStatusDisconn, 192);

    ui_ProjectHeadingLabel = lv_label_create(ui_TopPanel);
    lv_obj_set_width(ui_ProjectHeadingLabel, 209);
    lv_obj_set_height(ui_ProjectHeadingLabel, 28);
    lv_obj_set_align(ui_ProjectHeadingLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ProjectHeadingLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_ProjectHeadingLabel, "TONEX Controller");
    lv_obj_set_style_text_color(ui_ProjectHeadingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProjectHeadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ProjectHeadingLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProjectHeadingLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Skins = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Skins);
    lv_obj_set_width(ui_Skins, 480);
    lv_obj_set_height(ui_Skins, 113);
    lv_obj_set_x(ui_Skins, 0);
    lv_obj_set_y(ui_Skins, -24);
    lv_obj_set_align(ui_Skins, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Skins, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SkinImage = lv_img_create(ui_Skins);
    lv_img_set_src(ui_SkinImage, &ui_img_skin_jcm_png);
    lv_obj_set_width(ui_SkinImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SkinImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SkinImage, 0);
    lv_obj_set_y(ui_SkinImage, -9);
    lv_obj_set_align(ui_SkinImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SkinImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SkinImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SkinImage, 192);

    ui_PresetHeadingLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_PresetHeadingLabel, 480);
    lv_obj_set_height(ui_PresetHeadingLabel, 38);
    lv_obj_set_x(ui_PresetHeadingLabel, 0);
    lv_obj_set_y(ui_PresetHeadingLabel, -98);
    lv_obj_set_align(ui_PresetHeadingLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PresetHeadingLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_PresetHeadingLabel, "Preset Name");
    lv_obj_add_flag(ui_PresetHeadingLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_PresetHeadingLabel, lv_color_hex(0xD1A60C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PresetHeadingLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PresetHeadingLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PresetHeadingLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BankTitleLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BankTitleLabel, 84);
    lv_obj_set_height(ui_BankTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BankTitleLabel, -189);
    lv_obj_set_y(ui_BankTitleLabel, -64);
    lv_obj_set_align(ui_BankTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BankTitleLabel, "BANK");
    lv_obj_set_style_text_color(ui_BankTitleLabel, lv_color_hex(0xD1A60C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BankTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BankTitleLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BankTitleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BankValueLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BankValueLabel, 92);
    lv_obj_set_height(ui_BankValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BankValueLabel, -189);
    lv_obj_set_y(ui_BankValueLabel, -35);
    lv_obj_set_align(ui_BankValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BankValueLabel, "1");
    lv_obj_set_style_text_color(ui_BankValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BankValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BankValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BankValueLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BPMTitleLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BPMTitleLabel, 73);
    lv_obj_set_height(ui_BPMTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BPMTitleLabel, 186);
    lv_obj_set_y(ui_BPMTitleLabel, -64);
    lv_obj_set_align(ui_BPMTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BPMTitleLabel, "BPM");
    lv_obj_set_style_text_color(ui_BPMTitleLabel, lv_color_hex(0xD1A60C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BPMTitleLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BPMTitleLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BPMTitleLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BPMValueLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BPMValueLabel, 92);
    lv_obj_set_height(ui_BPMValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BPMValueLabel, 187);
    lv_obj_set_y(ui_BPMValueLabel, -35);
    lv_obj_set_align(ui_BPMValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BPMValueLabel, "0");
    lv_obj_set_style_text_color(ui_BPMValueLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BPMValueLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BPMValueLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BPMValueLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BPMIndicator = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_BPMIndicator, 30);
    lv_obj_set_height(ui_BPMIndicator, 30);
    lv_obj_set_x(ui_BPMIndicator, 187);
    lv_obj_set_y(ui_BPMIndicator, -3);
    lv_obj_set_align(ui_BPMIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BPMIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BPMIndicator, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BPMIndicator, lv_color_hex(0xD1A60C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BPMIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_BPMIndicator, lv_color_hex(0xD1B44D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_BPMIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_BPMIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_BPMIndicator, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_BPMIndicator, lv_color_hex(0xD1C59A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_BPMIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BPMIndicator, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BPMIndicator, lv_color_hex(0xD1A60C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BPMIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BPMIndicator, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BPMIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_BPMIndicator, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_BPMIndicator, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PresetDetailsTextArea = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_PresetDetailsTextArea, 464);
    lv_obj_set_height(ui_PresetDetailsTextArea, 82);
    lv_obj_set_x(ui_PresetDetailsTextArea, -1);
    lv_obj_set_y(ui_PresetDetailsTextArea, 60);
    lv_obj_set_align(ui_PresetDetailsTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PresetDetailsTextArea, 128);
    lv_textarea_set_placeholder_text(ui_PresetDetailsTextArea, "Preset Description...");
    lv_obj_add_state(ui_PresetDetailsTextArea, LV_STATE_DISABLED);       /// States
    lv_obj_set_style_text_font(ui_PresetDetailsTextArea, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PresetDetailsTextArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PresetDetailsTextArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PresetDetailsTextArea, lv_color_hex(0x563F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PresetDetailsTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftArrow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_LeftArrow, &ui_img_arrow_left_png);
    lv_obj_set_width(ui_LeftArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LeftArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LeftArrow, -201);
    lv_obj_set_y(ui_LeftArrow, -13);
    lv_obj_set_align(ui_LeftArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LeftArrow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LeftArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RightArrow = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_RightArrow, &ui_img_arrow_right_png);
    lv_obj_set_width(ui_RightArrow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RightArrow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RightArrow, 182);
    lv_obj_set_y(ui_RightArrow, -17);
    lv_obj_set_align(ui_RightArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RightArrow, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RightArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EntryKeyboard = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_EntryKeyboard, 469);
    lv_obj_set_height(ui_EntryKeyboard, 222);
    lv_obj_set_x(ui_EntryKeyboard, 0);
    lv_obj_set_y(ui_EntryKeyboard, -53);
    lv_obj_set_align(ui_EntryKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EntryKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_OKTick = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_OKTick, &ui_img_tick_png);
    lv_obj_set_width(ui_OKTick, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OKTick, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OKTick, -1);
    lv_obj_set_y(ui_OKTick, 132);
    lv_obj_set_align(ui_OKTick, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OKTick, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_OKTick, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_OKTick, 192);

    lv_obj_add_event_cb(ui_PreviousButton, ui_event_PreviousButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PreviousContainer, ui_event_PreviousContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextButton, ui_event_NextButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextContainer, ui_event_NextContainer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IconEQ, ui_event_IconEQ, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IconGate, ui_event_IconGate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IconAmp, ui_event_IconAmp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IconCab, ui_event_IconCab, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IconComp, ui_event_IconComp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IconMod, ui_event_IconMod, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IconDelay, ui_event_IconDelay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IconReverb, ui_event_IconReverb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsImage, ui_event_SettingsImage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTStatusDisconn, ui_event_BTStatusDisconn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PresetHeadingLabel, ui_event_PresetHeadingLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PresetDetailsTextArea, ui_event_PresetDetailsTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LeftArrow, ui_event_LeftArrow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RightArrow, ui_event_RightArrow, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_EntryKeyboard, ui_PresetDetailsTextArea);
    lv_obj_add_event_cb(ui_EntryKeyboard, ui_event_EntryKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OKTick, ui_event_OKTick, LV_EVENT_ALL, NULL);

}
